import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <header className="w-full flex justify-between py-3 px-16  border-b-4 border-violet-700">
          {["part1", "part2"].map(item => (
            <article key={item} className="hover-text">
              {item}
            </article>
          ))}
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
